apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe
  template:
    metadata:
      labels:
        app: recipe
    spec:
      containers:
      - name: recipe-container
        image: mkayani461/recipe-finder:v1
        ports:
        - containerPort: 5000

