apiVersion: v1
kind: Service
metadata:
  name: recipe-service
spec:
  type: NodePort
  selector:
    app: recipe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001
